print('Enter your first integer.')
number1 = input()
print('Enter your second integer.')
number2 = input()
sum = int(number1) + int(number2)
diff = int(number1) - int(number2)
prod = int(number1)*int(number2)
print('The sum is ' + str(sum))
print('The diff is ' + str(diff))
print('The prod is ' + str(prod))